# Generated by Django 3.1.6 on 2025-01-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100, unique=True, verbose_name='Product ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_type', models.CharField(max_length=100, verbose_name='Product Type')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Product Image')),
            ],
        ),
    ]
