# Generated by Django 3.1.6 on 2025-01-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20250102_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='purchasehistory',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_company', models.CharField(max_length=200)),
                ('quantity_used', models.PositiveIntegerField()),
                ('date_used', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='backend.purchasehistory', to_field='company_name')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='backend.product')),
            ],
        ),
    ]
