# Generated by Django 3.1.6 on 2025-01-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20250102_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('units', models.IntegerField()),
                ('installation_location', models.CharField(max_length=255)),
                ('installed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_date', models.DateField()),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='backend.product')),
            ],
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductUsage',
        ),
    ]
