# Generated by Django 3.1.6 on 2025-01-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20250104_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstallation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='backend.product', to_field='product_id'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='backend.product', to_field='product_id'),
        ),
    ]
