# Generated by Django 3.1.6 on 2025-01-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20250104_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstallation',
            name='client_name',
            field=models.CharField(default=2025, max_length=255),
            preserve_default=False,
        ),
    ]
